return {
  'https://github.com/AndrewRadev/splitjoin.vim',
  'https://github.com/editorconfig/editorconfig-vim',
  'https://github.com/michaeljsmith/vim-indent-object',
  'https://github.com/pbnj/vim-ddgr',
  'https://github.com/romainl/vim-qf',
  'https://github.com/tpope/vim-commentary',
  'https://github.com/tpope/vim-dispatch',
  'https://github.com/tpope/vim-dotenv',
  'https://github.com/tpope/vim-eunuch',
  'https://github.com/tpope/vim-rsi',
  'https://github.com/tpope/vim-surround',
  'https://github.com/tpope/vim-unimpaired',
  'https://github.com/tpope/vim-vinegar',
  'https://github.com/wellle/targets.vim',
}
